import './globals.css'
import type { Metadata } from 'next'
import Header from "@/components/Header/header";
import SharedSvgs from "@/components/Svgs/Shared";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.svg",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body>
        <SharedSvgs />
        <Header />
        {children}
      </body>
    </html>
  )
}
